### ISSUE TITLE
Error 263 for command: close ./alarm.mp3 指定的设备未打开，或不被 MCI 所识别。

### ISSUE THREAD

**Issue by th3weird0** [greatcodeeer/iPhone-Pickup-Monitor#3]
老师这该怎么办

WinCMD>python run.py
欢迎使用iPhone取货预约助手，请合理使用工具
正在检查环境：
即将播放预约提示音，按任意键开始..._(此时并没有听到alarm.mp3)_

    Error 263 for command:
        close ./alarm.mp3
    指定的设备未打开，或不被 MCI 所识别。
Failed to close the file: ./alarm.mp3
Traceback (most recent call last):
  File "C:\py\iPhone-Pickup-Monitor-main\run.py", line 15, in <module>
    playsound(sound_alarm)
  File "J:\python\installer-path\lib\site-packages\playsound.py", line 72, in _playsoundWin
    winCommand(u'open {}'.format(sound))
  File "J:\python\installer-path\lib\site-packages\playsound.py", line 56, in winCommand
    errorCode = int(windll.winmm.mciSendStringW(command, buf, bufLen - 1, 0))  # use widestring version of the function
OSError: exception: access violation reading 0x0000000000000000

**Comment by greatcodeeer** [comment]
你的python版本是多少？如果是3.9，尝试降级到3.7或3.8。
参考：https://stackoverflow.com/questions/68826091/the-specified-device-is-not-open-or-is-not-recognized-by-mci

**Comment by th3weird0** [comment]
当前是最新3.10 stable 我去试试

**Comment by th3weird0** [comment]
![image](https://user-images.githubusercontent.com/68617067/137528132-a35b2484-e227-4258-b5c9-c4257f8e6d63.png)
分别用了373和386试了一下 还是这样子 然后我怀疑是project folder放在C的关系 换了个盘放 还是一样的错误

**Comment by greatcodeeer** [comment]
你的 playsound 是什么版本？跟我 requirements 里引用的是一致的吗？

**Comment by th3weird0** [comment]
你好 应该是的 打开requirements.txt内容写的是
playsound==1.3.0
requests==2.26.0
但你看我上面的图上门是一样的
![image](https://user-images.githubusercontent.com/68617067/137529123-99ed3232-09bf-4418-81ce-6e776e6bdb11.png)

怪事发生了
作者早点休息

**Comment by greatcodeeer** [comment]
试试在 cmd 或 powershell 里面运行，你这个环境跟我是一样的，win下怪事多

**Comment by th3weird0** [comment]
![image](https://user-images.githubusercontent.com/68617067/137529862-c3f0e287-d9b7-4e84-b796-c30aa613fce1.png)
![image](https://user-images.githubusercontent.com/68617067/137529902-f9cb6dde-a108-453c-800a-0dde3e4ba4c3.png)
;(

**Comment by greatcodeeer** [comment]
试试 playsound 的 1.2.2 版本
`pip install playsound==1.2.2`
