### ISSUE TITLE
建议集成chanify等推送工具来代替播放声音

### ISSUE THREAD

**Issue by liudaolunboluo** [greatcodeeer/iPhone-Pickup-Monitor#5]
1、M1下使用playsound会报错暂未找到原因，但是注释掉就可以使用了
2、人不在电脑前的时候抢到了也没有办法第一时间知道

**Comment by greatcodeeer** [comment]
触发通知在[这行](https://github.com/greatcodeeer/iPhone-Pickup-Monitor/blob/06a925f67c3db93abccc8a38a296b523788eeda8/run.py#L98)，有代码基础的话建议直接接入推送，我这尽量避免流程复杂化，doge，而且，从我的经验来看，守在电脑前效果拔群，所以声音通知是第一要务。

M1的报错信息是什么？

**Comment by liudaolunboluo** [comment]
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python', '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/playsound.py', 'file:///Users/zhangyunfan/Documents/iPhone-Pickup-Monitor/./alarm.mp3']' returned non-zero exit status 32.

**Comment by greatcodeeer** [comment]
你要用python3，而不是python2来运行它
