### ISSUE TITLE
建议：使用方糖推送代替铃声

### ISSUE THREAD

**Issue by tangxueming** [greatcodeeer/iPhone-Pickup-Monitor#9]
建议
 使用方糖推送代替铃声。
1. 铃声的原因，我运行的时候失败了，怒而删掉了铃声这部分代码
2. 方糖是一个http请求，没有额外的依赖。
3. 场景，现有代码应该是在本地运行，人在电脑前等铃声； 使用方糖推送，可以让代码运行在远程服务器（本地也可以），主要是人可以走开了。。
我fork后，针对自己的需求，改了一点流程，不好直接提pr（前面的选择流程都被我写死了，不需要交互）。

**Comment by greatcodeeer** [comment]
现在大部分推送服务都支持GET方式一键送达，直接在[这里](https://github.com/greatcodeeer/iPhone-Pickup-Monitor/blob/06a925f67c3db93abccc8a38a296b523788eeda8/run.py#L98) requests 一下就好了。

脚本的定位是“抢”，还是建议守在电脑旁，等待第三方推送再行动的时间约等于错过机会。
